# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0004_auto_20170614_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='words',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
