# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0007_games_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='rows',
        ),
        migrations.AddField(
            model_name='games',
            name='stopdate',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='games',
            name='unnecessary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='words',
            field=models.CharField(max_length=5000),
        ),
    ]
