# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0008_auto_20170621_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.GameAdmins'),
        ),
        migrations.DeleteModel(
            name='GameAdmins',
        ),
    ]
